[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.echo]
description = "Test echo with our binary"
script.main = "vendor/maelstrom test -w echo --bin target/release/maelstrom --node-count 1 --time-limit 10"
dependencies = ["build-release"]
