[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.echo]
description = "Test echo with our binary"
script.main = "vendor/maelstrom test -w echo --bin target/release/maelstrom --node-count 1 --time-limit 10"
dependencies = ["build-release"]

[tasks.generate]
description = "Test generate ids with our binary"
script.main = "vendor/maelstrom test -w unique-ids --bin target/release/maelstrom --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition"
dependencies = ["build-release"]

[tasks.broadcast-single]
description = "Test broadcast single node"
script.main = "vendor/maelstrom test -w broadcast --bin target/release/maelstrom --node-count 1 --time-limit 20 --rate 10"
dependencies = ["build-release"]

[tasks.broadcast-multi]
description = "Test broadcast multi node"
script.main = "vendor/maelstrom test -w broadcast --bin target/release/maelstrom --node-count 5 --time-limit 20 --rate 10"
dependencies = ["build-release"]
